spring:
  application:
    name: projectservice
  cloud:
    config:
      uri: ${CONFIGSERVER_URI:http://localhost:8888}
      fail-fast: true
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:kafka:9092}

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URI:http://eurekaserver:8761/eureka/}
  instance:
    prefer-ip-address: true
