name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./project/pom.xml
          mvn clean package -f ./task/pom.xml
          mvn clean package -f ./user/pom.xml
          mvn clean package -f ./pdf/pom.xml
          mvn clean package -f ./norification/pom.xml
          mvn clean package -f ./github/pom.xml
          mvn clean package -f ./jwt/pom.xml

      - name: Docker Build and push for Project
        uses: docker/build-push-action@v4
        with:
          context: ./project
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/project:latest
            ghcr.io/${{ github.repository }}/project:${{ github.ref_name }}
            
      - name: Docker Build and push for Task
        uses: docker/build-push-action@v4
        with:
          context: ./task
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/task:latest
            ghcr.io/${{ github.repository }}/task:${{ github.ref_name }}
            
      - name: Docker Build and push for User
        uses: docker/build-push-action@v4
        with:
          context: ./user
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/user:latest
            ghcr.io/${{ github.repository }}/user:${{ github.ref_name }}
            
      - name: Docker Build and push for Pdf
        uses: docker/build-push-action@v4
        with:
          context: ./pdf
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/pdf:latest
            ghcr.io/${{ github.repository }}/pdf:${{ github.ref_name }}
            
      - name: Docker Build and push for Norification
        uses: docker/build-push-action@v4
        with:
          context: ./norification
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/norification:latest
            ghcr.io/${{ github.repository }}/norification:${{ github.ref_name }}
            
      - name: Docker Build and push for Github
        uses: docker/build-push-action@v4
        with:
          context: ./github
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/github:latest
            ghcr.io/${{ github.repository }}/github:${{ github.ref_name }}
            
      - name: Docker Build and push for Jwt
        uses: docker/build-push-action@v4
        with:
          context: ./jwt
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/jwt:latest
            ghcr.io/${{ github.repository }}/jwt:${{ github.ref_name }}
            
