server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: project
          uri: http://localhost:8082
          predicates:
            - Path=/projects/**, 
        - id: task
          uri: http://localhost:8083
          predicates:
            - Path=/tasks/**, 
        - id: user
          uri: http://localhost:8084
          predicates:
            - Path=/users/**, 
        - id: pdf
          uri: http://localhost:8085
          predicates:
            - Path=/pdfs/**, 
        - id: norification
          uri: http://localhost:8086
          predicates:
            - Path=, 
        - id: github
          uri: http://localhost:8087
          predicates:
            - Path=, 
        - id: jwt
          uri: http://localhost:8088
          predicates:
            - Path=/jwts/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: project
          uri: http://project:8080
          predicates:
            - Path=/projects/**, 
        - id: task
          uri: http://task:8080
          predicates:
            - Path=/tasks/**, 
        - id: user
          uri: http://user:8080
          predicates:
            - Path=/users/**, 
        - id: pdf
          uri: http://pdf:8080
          predicates:
            - Path=/pdfs/**, 
        - id: norification
          uri: http://norification:8080
          predicates:
            - Path=, 
        - id: github
          uri: http://github:8080
          predicates:
            - Path=, 
        - id: jwt
          uri: http://jwt:8080
          predicates:
            - Path=/jwts/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
