apiVersion: apps/v1
kind: Deployment
metadata:
  name: norification
  labels:
    app: norification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: norification
  template:
    metadata:
      labels:
        app: norification
    spec:
      containers:
        - name: norification
          image: "username/norification:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
